################################################
# Server configurations
################################################
server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8080


################################################
# Application (global) configurations
################################################
application:
    # License path
    # Absolute path to GroupDocs license file
    licensePath: E:/rabota/NewTeam/lic/GroupDocs.Total.Java.lic


################################################
# GroupDocs.Viewer configurations
################################################
viewer:
  # Directory where all original files are stored, by default the App_Data folder which is placed in the project root is used
  filesDirectory: /App_Data/
  # Fonts path
  # Absolute path to custom fonts directory
  fontsDirectory: ''
  # Default document
  # Absolute or relative path to default document
  defaultDocument: ''
  # HTML rendering mode
  # Set false for image mode
  # Set true for HTML mode
  htmlMode: true
  # Pages preload
  # How many pages from a document should be loaded, remaining pages will be loaded on page scrolling
  # Set 0 to load all pages at once
  preloadPageCount: 0
  # File rewriting on document uploading
  # Set false to keep both files
  # Set true to replace files with same name
  rewrite: true
  # Document zoom
  # Set false to disable document zooming
  zoom: true
  # Page navigation
  # Set false to disable document navigation (go to next, previous, last and first page)
  pageSelector: true
  # Document search
  # Set false to disable document text search
  search: true
  # Thumbnails
  # Set false to disable thumbnails
  thumbnails: true
  # Page rotation
  # Set false to disable pages rotation
  rotate: true
  # Document download
  # Set false to disable document download
  download: true
  # Document upload
  # Set false to disable document upload
  upload: true
  # Document print
  # Set false to disable document print
  print: true
  # File browser
  # Set false to disable document browse
  browse: true

################################################
# GroupDocs.Signature configurations
################################################
signature:
  # Directory where all original files are stored, by default the App_Data folder which is placed in the project root is used
  filesDirectory: /App_Data/
  # Directory where all signed documents are stored, if empty - will be created inside the filesDirectory
  outputDirectory: ''
  # Directory where all signature data such as digital certificates, images, stamps etc. are stored, if empty - signatureData directory will be created inside the filesDirectory
  dataDirectory: ''
  # Enable/disable text signature
  textSignature: true
  # Enable/disable image signature
  imageSignature: true
  # Enable/disable digital signature
  digitalSignature: true
  # Enable/disable QR-Code signature
  qrCodeSignature: true
  # Enable/disable Barcode signature
  barCodeSignature: true
  # Enable/disable Stamp signature
  stampSignature: true
  # Enable/disable original document downloading
  downloadOriginal: true
  # Enable/disable signed document downloading
  downloadSigned: true